title: hyperactivekarma
description: My very nice blog
author: "hyperactivekarma"

theme: minima

base_url: 
repository: hyperactivekarma/hyperactivekarma.github.io

# Minima social links
github_username: hyperactivekarma
linkedin_username: ""  # opcional
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
